-- =============================================================================
-- V001 — Initial schema for LasanthaPOS
--
-- Idempotent: safe to run against a DB that already has these tables
-- (e.g. one already set up by EF Core's db.Database.Migrate()).
--
-- Also records the EF Core InitialCreate migration in __EFMigrationsHistory
-- so the API's auto-migrate startup step skips it cleanly when this script
-- has run first (standalone deploy without the API container).
-- =============================================================================

-- ---------------------------------------------------------------------------
-- EF Core migration history (EF creates this too; IF NOT EXISTS is harmless)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId"    character varying(150) NOT NULL,
    "ProductVersion" character varying(32)  NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

-- Mark the EF Core initial migration as applied so the API won't re-run it
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260403164529_InitialCreate', '10.0.5')
ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- Core lookup tables
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "Categories" (
    "Id"   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" text    NOT NULL
);

CREATE TABLE IF NOT EXISTS "Suppliers" (
    "Id"           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name"         text    NOT NULL,
    "ContactPhone" text    NOT NULL,
    "Email"        text    NOT NULL
);

-- ---------------------------------------------------------------------------
-- People tables
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "Customers" (
    "Id"            integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name"          text        NOT NULL,
    "Phone"         text        NOT NULL,
    "Email"         text        NOT NULL,
    "LoyaltyCardId" text        NOT NULL,
    "LoyaltyPoints" integer     NOT NULL DEFAULT 0,
    "RegisteredAt"  timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "Users" (
    "Id"           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Username"     text    NOT NULL,
    "PasswordHash" text    NOT NULL,
    "Role"         text    NOT NULL DEFAULT 'Cashier',
    "FullName"     text    NOT NULL,
    "IsActive"     boolean NOT NULL DEFAULT TRUE
);

-- ---------------------------------------------------------------------------
-- Inventory
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "Products" (
    "Id"               integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ItemCode"         text        NOT NULL,
    "Name"             text        NOT NULL,
    "CategoryId"       integer     NOT NULL REFERENCES "Categories"("Id") ON DELETE CASCADE,
    "SupplierId"       integer     NOT NULL REFERENCES "Suppliers"("Id")  ON DELETE CASCADE,
    "BuyingPrice"      numeric     NOT NULL,
    "SellingPrice"     numeric     NOT NULL,
    "Quantity"         integer     NOT NULL DEFAULT 0,
    "ReorderThreshold" integer     NOT NULL DEFAULT 5,
    "PurchaseDate"     timestamptz NOT NULL,
    "ExpirationDate"   timestamptz,
    "WarrantyMonths"   integer
);

-- ---------------------------------------------------------------------------
-- Sales
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "Sales" (
    "Id"             integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ReceiptNumber"  text        NOT NULL,
    "CustomerId"     integer     REFERENCES "Customers"("Id"),
    "SaleDate"       timestamptz NOT NULL DEFAULT NOW(),
    "SubTotal"       numeric     NOT NULL,
    "DiscountAmount" numeric     NOT NULL DEFAULT 0,
    "TaxAmount"      numeric     NOT NULL DEFAULT 0,
    "Total"          numeric     NOT NULL,
    "PaymentMethod"  text        NOT NULL DEFAULT 'Cash',
    "AmountPaid"     numeric     NOT NULL,
    "Change"         numeric     NOT NULL DEFAULT 0,
    "PointsEarned"   integer     NOT NULL DEFAULT 0,
    "PointsRedeemed" integer     NOT NULL DEFAULT 0,
    "CreatedBy"      text        NOT NULL
);

CREATE TABLE IF NOT EXISTS "SaleItems" (
    "Id"             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SaleId"         integer NOT NULL REFERENCES "Sales"("Id")    ON DELETE CASCADE,
    "ProductId"      integer NOT NULL REFERENCES "Products"("Id") ON DELETE CASCADE,
    "ItemCode"       text    NOT NULL,
    "ProductName"    text    NOT NULL,
    "Quantity"       integer NOT NULL,
    "UnitPrice"      numeric NOT NULL,
    "DiscountAmount" numeric NOT NULL DEFAULT 0,
    "LineTotal"      numeric NOT NULL
);

-- ---------------------------------------------------------------------------
-- Warranties
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "Warranties" (
    "Id"         integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SaleItemId" integer     NOT NULL REFERENCES "SaleItems"("Id")  ON DELETE CASCADE,
    "CustomerId" integer     NOT NULL REFERENCES "Customers"("Id")  ON DELETE CASCADE,
    "ProductId"  integer     NOT NULL REFERENCES "Products"("Id")   ON DELETE CASCADE,
    "StartDate"  timestamptz NOT NULL,
    "EndDate"    timestamptz NOT NULL,
    "Terms"      text        NOT NULL DEFAULT '',
    "Status"     text        NOT NULL DEFAULT 'Active',
    "ClaimNotes" text        NOT NULL DEFAULT ''
);

-- ---------------------------------------------------------------------------
-- Indexes  (idempotent via IF NOT EXISTS)
-- ---------------------------------------------------------------------------

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Customers_LoyaltyCardId" ON "Customers"("LoyaltyCardId");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Products_ItemCode"    ON "Products"("ItemCode");
CREATE        INDEX IF NOT EXISTS "IX_Products_CategoryId"  ON "Products"("CategoryId");
CREATE        INDEX IF NOT EXISTS "IX_Products_SupplierId"  ON "Products"("SupplierId");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Sales_ReceiptNumber"  ON "Sales"("ReceiptNumber");
CREATE        INDEX IF NOT EXISTS "IX_Sales_CustomerId"     ON "Sales"("CustomerId");

CREATE INDEX IF NOT EXISTS "IX_SaleItems_SaleId"    ON "SaleItems"("SaleId");
CREATE INDEX IF NOT EXISTS "IX_SaleItems_ProductId" ON "SaleItems"("ProductId");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_Username" ON "Users"("Username");

CREATE INDEX IF NOT EXISTS "IX_Warranties_CustomerId"  ON "Warranties"("CustomerId");
CREATE INDEX IF NOT EXISTS "IX_Warranties_ProductId"   ON "Warranties"("ProductId");
CREATE INDEX IF NOT EXISTS "IX_Warranties_SaleItemId"  ON "Warranties"("SaleItemId");
